import React from 'react'
import Head from 'next/head'

const Layout = ({children}:{children:React.ReactNode}) => {
    return (
        <>
        <Head>
            <title>Portfolio | John Henrich Dela Pena</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        {children}
        </>
    )
}

export default Layout
